//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartManufacturingLocal_HIP_PLC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEST24415Entities : DbContext
    {
        public DBEST24415Entities()
            : base("name=DBEST24415Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EST_Machine> EST_Machine { get; set; }
        public virtual DbSet<EST_Production> EST_Production { get; set; }
        public virtual DbSet<EST_Setup> EST_Setup { get; set; }
    }
}
